language: node_js

node_js:
  - "node"

before_install:
  - npm install -g npm@latest

jobs:
  include:
    - stage: test
      script:
        - npm run test
      name: Compile and check for style errors
    - stage: deploy
      name: Deploy to GitHub Pages
      script:
        - npm run build
        - cp README.deploy dist/README.md
      deploy:
        provider: pages
        repo: srcery-colors/srcery-colors.github.io
        target-branch: master
        local-dir: dist/
        skip-cleanup: true
        github-token: $GITHUB_TOKEN # Set in the settings page of your repository, as a secure variable
        keep-history: true
        on:
          branch: master

notifications:
  email: false
