language: node_js

node_js:
  - "node"

cache:
  directories:
    - "npm"
    - "vendor"

before_install:
  - gem update --system
  - npm install -g npm@latest

before_script:
  - bundle install

jobs:
  include:
    - stage: test
      script:
        - npm test
        - npm run build:dev
        - npm run build:prod
        - bundle exec jekyll build --profile
      name: Compile and check for style errors
    - stage: deploy
      name: Deploy to GitHub Pages
      script:
        - npm run build:prod
        - bundle exec jekyll build
        - touch _site/.nojekyll
      deploy:
        provider: pages
        repo: srcery-colors/srcery-colors.github.io
        target-branch: master
        local-dir: _site/
        skip-cleanup: true
        github-token: $GITHUB_TOKEN  # Set in the settings page of your repository, as a secure variable
        keep-history: true
        on:
          branch: master

notifications:
    email: false
