name: Deploy

on:
  push:
    branches:
      - master

jobs:
  deploy:
    needs: test_and_build

    name: Deploy to GitHub Pages
    runs-on: ubuntu-latest

    steps:
      - name: Download built dist folder
        uses: actions/download-artifact@v1
        with:
          name: dist

      - name: Deploy
        uses: peaceiris/actions-gh-pages@v3
        with:
          external_repository: srcery-colors/srcery-colors.github.io
          deploy_key: ${{ secrets.SRCERY_DEPLOY_KEY }}
          publish_branch: master # deploying branch
          publish_dir: ./dist
