name: Build & Deploy

on:
  push:
    branches:
      - master

jobs:
  build:
    name: Compile Source Files
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Use Node.js
        uses: actions/setup-node@v2.1.2

      - name: Install Dependencies
        run: npm ci

      - name: Build Site
        run: npm run build --if-present

      - name: Add README.md
        run: cp README.deploy dist/README.md

      - name: Upload Compiled Files
        uses: actions/upload-artifact@v2.2.1
        with:
          name: dist
          path: ./dist

  deploy:
    name: Deploy to GitHub Pages
    runs-on: ubuntu-latest

    needs: build

    steps:
      - name: Download Compiled Files
        uses: actions/download-artifact@v2.0.5
        with:
          name: dist
          path: ./dist

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          deploy_key: ${{ secrets.SRCERY_DEPLOY_KEY }}
          publish_branch: site # deploying branch
          publish_dir: ./dist
